name: kubescape-repo-scan

on: 
   push:
    branches: [ "main" ]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: orrgato/Kubescape-github-action@repo-scan
        with:
          scanRepository: "yes"
          accountGUID: ${{secrets.ACCOUNT_GUID}}
