name: kubescape-with-exceptions-scan

on:
  push:
    branches: [ "main" ]
    
jobs:
  kubescape-exception:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: orrgato/Kubescape-github-action@add-exception
        with:
          args: "--format junit --output results.xml"
          files: "kubernetes-manifest/deployment.yaml"
          threshold: 50
          framework: |
            nsa,devopsbest
          exceptions: exceptions/exclude-NSA-framework.json
