name: kubescape-with-exceptions-scan

on:
  push:
    branches: [ "main" ]
    
jobs:
  kubescape-exception:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: orrgato/Kubescape-github-action@add-exception
        with:
          args: "--format junit --output results.xml"
          files: "kubernetes-manifest/deployment.yaml"
          threshold: 50
          framework: |
            nsa,devopsbest
      - name: Archive kubescape scan results
        uses: actions/upload-artifact@v2
        with:
          name: kubescape-scan-report
          path: results/results.xml
