name: kubescape-scan

on: 
   push:
    branches: [ "main" ]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: kubescape/github-action@main
        with:
          files: "kubernetes-manifest/deployment.yaml"
          threshold: 50
          framework: |
            nsa,devopsbest
          # control: |
          #   Configured liveness probe,Pods in default namespace,Bash/cmd inside container       

